Added a http5xx_alarm attribute at target group
ridi/terraform-modules pull request #4
Opened 2020-03-24 13:57 UTC by m0ai

## 변경사항 
- target group 에 http5xx_alarm attribute 를 추가하였습니다.
- README.md에 해당 attribute의 관한 설명을 추가하였습니다.

2020-03-25 04:12 UTC, imkitae requested changes

2020-03-25 04:12 UTC, imkitae commented on aws/alb/variables.tf
> +  #       unhealthy_threshold = number (default = 5)
health check의 주석을 복사하고 수정을 안하신 것 같네요.

2020-03-25 04:12 UTC, imkitae commented on aws/alb/main.tf
> +    if lookup(lookup(target_group, "health_check", {}), "enabled", true)
Python의 Ternary Operator같은 느낌으로 한 줄에 적는게 좋아보이는데, 만약 여러 줄로 적을거면 if는 들여쓰기를 하는 편이 좋을 것 같습니다. 혹시 terraform format에서 들여쓰기를 막는다면 그냥 이대로 두고요

2020-03-25 04:12 UTC, imkitae commented on aws/alb/main.tf
> +resource "aws_cloudwatch_metric_alarm" "http5xx_alarm" {
alarm 리소스이므로 http5xx라고만 해도 충분할 것 같습니다.

2020-03-25 04:12 UTC, imkitae commented on aws/alb/README.md
> +      http5xx_alarm    = { enabled = false }
health_check의 경우 Lambda target group과 Instance target group은 설정 형식이 다릅니다. alarm은 그렇지 않을 것 같은데 확인해보셨나요?

2020-03-25 04:12 UTC, imkitae commented on aws/alb/main.tf
> +  # { target_group_name => target_http5xx_alarm_options }
(주석이지만..) target_http5xx_alarm_options -> http5xx_alarm_options 가 자연스러울 것 같습니다.

2020-03-25 04:12 UTC, imkitae commented on aws/alb/README.md
> +      comparison_operator = string (default = "GreaterThanThreshold" )
GreaterThanThreshold를 다른 값으로 설정할 일이 없을 듯 합니다. 설정할 수 있는 값이 많을 수록 좋긴 한데 그만큼 복잡해지므로, 고정된 템플릿을 제공하고 수치만 변경한다는 의도로 숫자 값만 설정하게 두고 다른 값은 빼는 게 어떨까요?

정교한 설정을 가능하게 할 의도라면 차라리 statistic도 추가하는게 낫겠습니다. 아마 운영하다보면 statistic을 변경할 경우가 더 많을 거에요 (평균 값이나 최대값으로 설정하는 경우)

그리고 수치 중에 evaluation_periods를 추가하면 좋겠습니다.

2020-03-25 04:31 UTC, m0ai commented on aws/alb/main.tf
> +    if lookup(lookup(target_group, "health_check", {}), "enabled", true)
terraform format 에서 들여쓰기를 막네요. 

변경하게된 배경은  한줄로 하면 너무 한 행이 길어져서 가독성이 너무 떨어져서 두줄로 변경하였습니다.

2020-03-25 04:41 UTC, m0ai commented on aws/alb/README.md
> +      comparison_operator = string (default = "GreaterThanThreshold" )
statistic 를 추가하지 않은 이유는 http5xx 메트릭스 같은 경우는 `statistic = sum` 으로 권장하고 있어서 이 가변적으로 설정을 제공할 필요는 없을 것 같습니다.

comparison_operator 는 모듈 사용자 측면에서 GreaterThanOrEqualToThreshold 을 선호하지 않을까 생각되서 가변적인 설정으로 두었는데요.  말씀하신 것 처럼 고정된 템플릿을 제공하는 방향이 깔끔하고 좋을 것 같네요. 

`evaluation_periods` 을 가변적이게 설정할 수 있도록 변경해놓겠습니다 :+1:

2020-03-25 05:01 UTC, m0ai commented on aws/alb/README.md
> +      http5xx_alarm    = { enabled = false }
네 알람은 따로 instance와 lambda의 구분을 두지 않습니다. aws_cloudwatch_metric_alarm 리소스에서도 참조하는 메트릭스에서 어떤 타입인지 구분을 하지 않고요.

2020-03-25 06:00 UTC, imkitae commented on aws/alb/README.md
> +      http5xx_alarm    = { enabled = false }
그렇다면 http5xx_alarm의 값은 instance-api의 것과 동일해야 할 것 같네요.

2020-03-25 06:03 UTC, m0ai commented on aws/alb/README.md
> +      http5xx_alarm    = { enabled = false }
아 저는 이 README.mr가 example처럼 다양하게 사용할 수 있다 라는 것을 알기위해 적어놓았다구 생각했네요. 마치 serverless.yml example 처럼요. 람다에서도 어쨋든 health check를 사용할 수 있긴하니까요 ㅎㅎ

2020-03-25 06:07 UTC, imkitae commented on aws/alb/main.tf
> +  alarm_description = "The http 5xx code count of target group '${each.key}'"
`The count of http 5xx response from target group '~'`가 좋을 것 같습니다. (어떻게 수정하던 간에 `response의 수`로)

2020-03-25 06:16 UTC, m0ai commented on aws/alb/main.tf
> +  alarm_description = "The http 5xx code count of target group '${each.key}'"
수정 완료하였습니다!

2020-03-25 06:18 UTC, imkitae commented on aws/alb/README.md
> +      enabled            = bool (default = true)
enabled를 참조하는 것이 없는 것 같은데.. 맞나요? 지금은 5xx 알람의 생성 여부가 metrix_alarm_actions 변수 유무로만 결정되는 것으로 보입니다.

알람 리소스의 actions_enabled에 연결시키면 될 것 같은데, 저도 설정한지 오래되서 잘 모르겠네요.. 참고로 기존 unhealthy host 알람은 alarn sns를 설정하는 경우 무조건 전체 target group들에 대해 알람을 설정합니다. 선택적으로 부여하지 않아요.

2020-03-25 06:31 UTC, m0ai commented on aws/alb/README.md
> +      enabled            = bool (default = true)
http5xx_alarm_target_groups variable 를 생성할때  http5xx_alarm.enabled 를 참조하여 http5xx alarm 을 생성할 target을 추려냅니다. (아래 코드 참고 )

unhealthy host 알람도 enabled을 사용하여 선택적으로 부여하고 있지 않나요?  select/provision에서의  lambda target group은 enabled = false 으로 선택적으로 부여하는 것을 보고 http5xx alarm도 동일하게 인터페이스를 구현하였습니다.

```hcl
  http5xx_alarm_target_groups =  ... 
     if lookup(lookup(target_group, "http5xx_alarm", {}), "enabled"
     ...

// origin > https://github.com/ridi/terraform-modules/pull/4/files#diff-9ab44b2988315fb3386b792a14d2445bR50
```

2020-03-26 06:36 UTC, imkitae commented on aws/alb/README.md
> +      enabled            = bool (default = true)
람다 함수에 한해 enabled = false이면 누락시키기 위한 설정입니다. 그건 람다 함수이면서 enabled = false이면 데이터가 쌓이지 않아 지표 missing이 뜨기 때문입니다. target group은 그렇게 부분적으로 설정할 필요가 없을 것 같네요.

2020-03-26 06:39 UTC, imkitae commented on aws/alb/README.md
> +      enabled            = bool (default = true)
정리하면 health check 옵션은 람다의 특수성 때문에 일반 EC2와 형식이 달라서 구분하고 있고, enabled가 그런 특수한 변수 중 하나입니다.

타겟 그룹은 그룹 타겟이 람다건 EC2건 상관없이 동일하게 취급할 수 있으므로 그냥 일괄적으로 처리하면 되고, 설정과 코드가 간편해져서 그 편이 더 낫다고 생각합니다.

2020-03-26 06:45 UTC, imkitae commented on aws/alb/README.md
> +      enabled            = bool (default = true)
기억이 가물가물해서 다시 찾아보니 enabled가 람다만 설정하는 값은 아니네요. 처음 의도는 람다의 경우 enabled = false를 설정하는 일이 많아서 선택적 제외를 위해 그렇게 구현했는데, 굳이 그렇게 한정시킬 필요는 없을 듯 합니다. 그냥 영준님이 작성한 데로 진행해도 될 것 같네요.

2020-03-26 06:58 UTC, merged

2020-03-26 07:02 UTC, m0ai commented on aws/alb/README.md
> +      enabled            = bool (default = true)
확인감사드립니다. :bow: 
저는 단순하게 각 서비스마다 health check가 필요하지 않든 enabled 필드가 있던 것으로 알고 있었어서 이를 계승(?)했었습니다. 타겟 그룹마다 알람도 선택적으로 할 수 있도록이요 👀